export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST';
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
export const ADMIN_SIGNIN_FAILURE = 'ADMIN_SIGNIN_FAILURE';
export const ADMIN_SIGNOUT = 'ADMIN_SIGNOUT';

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILURE = 'USER_SIGNIN_FAILURE';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const DRIVER_SIGNUP_REQUEST = 'DRIVER_SIGNUP_REQUEST';
export const DRIVER_SIGNUP_SUCCESS = 'DRIVER_SIGNUP_SUCCESS';
export const DRIVER_SIGNUP_FAILURE = 'DRIVER_SIGNUP_FAILURE';

export const DRIVER_SIGNIN_REQUEST = 'DRIVER_SIGNIN_REQUEST';
export const DRIVER_SIGNIN_SUCCESS = 'DRIVER_SIGNIN_SUCCESS';
export const DRIVER_SIGNIN_FAILURE = 'DRIVER_SIGNIN_FAILURE';
export const DRIVER_SIGNOUT = 'DRIVER_SIGNOUT';

export const DRIVER_DETAILS_REQUEST = 'DRIVER_DETAILS_REQUEST';
export const DRIVER_DETAILS_SUCCESS = 'DRIVER_DETAILS_SUCCESS';
export const DRIVER_DETAILS_FAILURE = 'DRIVER_DETAILS_FAILURE';