export const CITY_GET_REQUEST = 'CITY_GET_REQUEST';
export const CITY_GET_SUCCESS = 'CITY_GET_SUCCESS';
export const CITY_GET_FAILURE = 'CITY_GET_FAILURE';

export const CITY_ADD_REQUEST = 'CITY_ADD_REQUEST';
export const CITY_ADD_SUCCESS = 'CITY_ADD_SUCCESS';
export const CITY_ADD_FAILURE = 'CITY_ADD_FAILURE';