export const RATING_ADD_REQUEST = 'RATING_ADD_REQUEST';
export const RATING_ADD_SUCCESS = 'RATING_ADD_SUCCESS';
export const RATING_ADD_FAILURE = 'RATING_ADD_FAILURE';

export const RATING_GET_REQUEST = 'RATING_GET_REQUEST';
export const RATING_GET_SUCCESS = 'RATING_GET_SUCCESS';
export const RATING_GET_FAILURE = 'RATING_GET_FAILURE';