export const RIDE_ADD_REQUEST = 'RIDE_ADD_REQUEST';
export const RIDE_ADD_SUCCESS = 'RIDE_ADD_SUCCESS';
export const RIDE_ADD_FAILURE = 'RIDE_ADD_FAILURE';

export const RIDE_GET_REQUEST = 'RIDE_GET_REQUEST';
export const RIDE_GET_SUCCESS = 'RIDE_GET_SUCCESS';
export const RIDE_GET_FAILURE = 'RIDE_GET_FAILURE';