export const STATE_GET_REQUEST = 'STATE_GET_REQUEST';
export const STATE_GET_SUCCESS = 'STATE_GET_SUCCESS';
export const STATE_GET_FAILURE = 'STATE_GET_FAILURE';

export const STATE_ADD_REQUEST = 'STATE_ADD_REQUEST';
export const STATE_ADD_SUCCESS = 'STATE_ADD_SUCCESS';
export const STATE_ADD_FAILURE = 'STATE_ADD_FAILURE';