export const VEHICLE_ADD_REQUEST = 'VEHICLE_ADD_REQUEST';
export const VEHICLE_ADD_SUCCESS = 'VEHICLE_ADD_SUCCESS';
export const VEHICLE_ADD_FAILURE = 'VEHICLE_ADD_FAILURE';

export const VEHICLE_GET_REQUEST = 'VEHICLE_GET_REQUEST';
export const VEHICLE_GET_SUCCESS = 'VEHICLE_GET_SUCCESS';
export const VEHICLE_GET_FAILURE = 'VEHICLE_GET_FAILURE';